common: &common
    access_key_id: your_access_key_id
    secret_access_key: your_secret_access_key

development:
    <<: *common
    bucket: bucket_name

test:
    <<: *common
    bucket: bucket_name_test

production:
    <<: *common
    bucket: bucket_name_production